#!/bin/bash

set -eou pipefail

JIRATAG=$(git rev-parse --abbrev-ref HEAD | grep -Eo '[A-Z]+-[0-9]+' || true)

if ! [ "$JIRATAG" ]; then
    exit 0
fi

SUBJECT="$(git show -s --pretty=tformat:%s | sed "s/^${JIRATAG} //")"
BODY="$(git show -s --pretty=tformat:%b)"

git commit --amend -m "${SUBJECT}" -m "${BODY}" -m "${JIRATAG} #done"
exit 0
