#!/usr/bin/env bash

set -euo pipefail

JIRATAG=$(git rev-parse --abbrev-ref HEAD | grep -Eo '[A-Z]+-[0-9]+')

if [[ -z $JIRATAG ]]; then
    echo "Can not find JIRA tag in branch name" 1>&2
    exit 0
fi

SUBJECT=$(git show -s --pretty=tformat:%s | sed "s/^${JIRATAG} //")
BODY=$(git show -s --pretty=tformat:%b)

git commit --amend -m "${SUBJECT}" -m "${BODY}" -m "${JIRATAG} #done"
